1. The HelloWorld replacement

a) Write a program that prints the numbers from 1 to 100. But for multiples of three print "Hello" instead of the number and for the multiples of five print "World". For numbers which are multiples of both three and five print "HelloWorld".

b) Put the result in a tuple and substitute "Hello" with "Python" and "World" with "Works".

In [7]:
for i in list(range(1,100)):
    if i % 3 == 0 and i % 5 == 0:
        print ("HelloWorld")
    elif i % 3 == 0:
        print("Hello")
    elif i % 5 == 0:
        print("world")
    else:
        print(i)

1
2
Hello
4
world
Hello
7
8
Hello
world
11
Hello
13
14
HelloWorld
16
17
Hello
19
world
Hello
22
23
Hello
world
26
Hello
28
29
HelloWorld
31
32
Hello
34
world
Hello
37
38
Hello
world
41
Hello
43
44
HelloWorld
46
47
Hello
49
world
Hello
52
53
Hello
world
56
Hello
58
59
HelloWorld
61
62
Hello
64
world
Hello
67
68
Hello
world
71
Hello
73
74
HelloWorld
76
77
Hello
79
world
Hello
82
83
Hello
world
86
Hello
88
89
HelloWorld
91
92
Hello
94
world
Hello
97
98
Hello

2\. The swap function

Write a function that swap the values of two input variables x and y (whatever the type). Try to do that also without a temporary variable

In [16]:
def swap_temp(x, y):
    temp = x
    x = y
    y = temp
    return (x, y)

swap_func(4,2)

(2, 4)

In [17]:
def swap_func(x, y):
    return (y ,x)

swap_temp(3,2)

(2, 3)

3\. Computing the distance

Write a function that calculates and returns the euclidean distance between two points *u* and *v*, where *u* and *v* are both 2-tuples *(x,y)*. For example, if *u=(3,0)* and *v=(0,4)*, the function should return 5

In [11]:
def eucliden_dis (p1, p2):
    d = (p1[0]-p2[0])**2+(p1[1]-p2[1])**2
    return d**(1/2)
  
distance = calc_distance((3,0), (0, 4))
print (distance)

5.0

4\. Counting letters

Write a program to calculate the number of times each character occurs in a given string *s*. Ignore differences in capitalization

In [30]:
s = "Write a program that prints the numbers from 1 to 100. \
But for multiples of three print Hello instead of the number and for the multiples of five print World. \
For numbers which are multiples of both three and five print HelloWorld."

for i in s:
    counter={}
    counter[i]=s.count(i)
    print (counter)

{'W': 3}
{'r': 19}
{'i': 12}
{'t': 19}
{'e': 20}
{' ': 41}
{'a': 7}
{' ': 41}
{'p': 8}
{'r': 19}
{'o': 15}
{'g': 1}
{'r': 19}
{'a': 7}
{'m': 8}
{' ': 41}
{'t': 19}
{'h': 9}
{'a': 7}
{'t': 19}
{' ': 41}
{'p': 8}
{'r': 19}
{'i': 12}
{'n': 10}
{'t': 19}
{'s': 7}
{' ': 41}
{'t': 19}
{'h': 9}
{'e': 20}
{' ': 41}
{'n': 10}
{'u': 7}
{'m': 8}
{'b': 4}
{'e': 20}
{'r': 19}
{'s': 7}
{' ': 41}
{'f': 9}
{'r': 19}
{'o': 15}
{'m': 8}
{' ': 41}
{'1': 2}
{' ': 41}
{'t': 19}
{'o': 15}
{' ': 41}
{'1': 2}
{'0': 2}
{'0': 2}
{'.': 3}
{' ': 41}
{'B': 1}
{'u': 7}
{'t': 19}
{' ': 41}
{'f': 9}
{'o': 15}
{'r': 19}
{' ': 41}
{'m': 8}
{'u': 7}
{'l': 12}
{'t': 19}
{'i': 12}
{'p': 8}
{'l': 12}
{'e': 20}
{'s': 7}
{' ': 41}
{'o': 15}
{'f': 9}
{' ': 41}
{'t': 19}
{'h': 9}
{'r': 19}
{'e': 20}
{'e': 20}
{' ': 41}
{'p': 8}
{'r': 19}
{'i': 12}
{'n': 10}
{'t': 19}
{' ': 41}
{'H': 2}
{'e': 20}
{'l': 12}
{'l': 12}
{'o': 15}
{' ': 41}
{'i': 12}
{'n': 10}
{'s': 7}
{'t': 19}
{'e': 20}
{'a': 7}
{'d': 5}
{' ': 41}
{'o': 15}
{'f': 9}
{' ': 41}
{'t': 19}
{'h': 9}
{'e': 20}
{' ': 41}
{'n': 10}
{'u': 7}
{'m': 8}
{'b': 4}
{'e': 20}
{'r': 19}
{' ': 41}
{'a': 7}
{'n': 10}
{'d': 5}
{' ': 41}
{'f': 9}
{'o': 15}
{'r': 19}
{' ': 41}
{'t': 19}
{'h': 9}
{'e': 20}
{' ': 41}
{'m': 8}
{'u': 7}
{'l': 12}
{'t': 19}
{'i': 12}
{'p': 8}
{'l': 12}
{'e': 20}
{'s': 7}
{' ': 41}
{'o': 15}
{'f': 9}
{' ': 41}
{'f': 9}
{'i': 12}
{'v': 2}
{'e': 20}
{' ': 41}
{'p': 8}
{'r': 19}
{'i': 12}
{'n': 10}
{'t': 19}
{' ': 41}
{'W': 3}
{'o': 15}
{'r': 19}
{'l': 12}
{'d': 5}
{'.': 3}
{' ': 41}
{'F': 1}
{'o': 15}
{'r': 19}
{' ': 41}
{'n': 10}
{'u': 7}
{'m': 8}
{'b': 4}
{'e': 20}
{'r': 19}
{'s': 7}
{' ': 41}
{'w': 1}
{'h': 9}
{'i': 12}
{'c': 1}
{'h': 9}
{' ': 41}
{'a': 7}
{'r': 19}
{'e': 20}
{' ': 41}
{'m': 8}
{'u': 7}
{'l': 12}
{'t': 19}
{'i': 12}
{'p': 8}
{'l': 12}
{'e': 20}
{'s': 7}
{' ': 41}
{'o': 15}
{'f': 9}
{' ': 41}
{'b': 4}
{'o': 15}
{'t': 19}
{'h': 9}
{' ': 41}
{'t': 19}
{'h': 9}
{'r': 19}
{'e': 20}
{'e': 20}
{' ': 41}
{'a': 7}
{'n': 10}
{'d': 5}
{' ': 41}
{'f': 9}
{'i': 12}
{'v': 2}
{'e': 20}
{' ': 41}
{'p': 8}
{'r': 19}
{'i': 12}
{'n': 10}
{'t': 19}
{' ': 41}
{'H': 2}
{'e': 20}
{'l': 12}
{'l': 12}
{'o': 15}
{'W': 3}
{'o': 15}
{'r': 19}
{'l': 12}
{'d': 5}
{'.': 3}

In [2]:
s = "Write a program that prints the numbers from 1 to 100. \
But for multiples of three print Hello instead of the number and for the multiples of five print World. \
For numbers which are multiples of both three and five print HelloWorld."

5\. Isolating the unique

Write a function that determines and count the unique numbers in the list:

In [5]:
l = [36, 45, 58, 3, 74, 96, 64, 45, 31, 10, 24, 19, 33, 86, 99, 18, 63, 70, 85,
 85, 63, 47, 56, 42, 70, 84, 88, 55, 20, 54, 8, 56, 51, 79, 81, 57, 37, 91,
 1, 84, 84, 36, 66, 9, 89, 50, 42, 91, 50, 95, 90, 98, 39, 16, 82, 31, 92, 41,
 45, 30, 66, 70, 34, 85, 94, 5, 3, 36, 72, 91, 84, 34, 87, 75, 53, 51, 20, 89, 51, 20]

Do the same without using user-defined functions, but exploiting only the Python data structures.

6\. Combination of functions

Write two functions - one that returns the square of a number, and one that returns the cube. Now write a third function that returns the number raised to the 6th power using the two previous functions.

7\. Cubes

Create a list of the cubes of x for x in *[0, 10]* using:

a) a for loop

b) a list comprehension

8\. Nested list comprehension

A Pythagorean triple is an integer solution to the Pythagorean theorem $a^2+b^2=c^2$. The first Pythagorean triple is (3,4,5). Find and put in a tuple all unique Pythagorean triples for the positive integers a, b and c less than 100.

9\. Normalization

Write a function that takes a tuple of numbers and returns it with the entries normalized to one